In [1]:
import sys
import numpy as np
sys.path.append('../')
from TwitterKeeper.Twitter_keeper import PullTweetsData
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd
from wordcloud import WordCloud
import matplotlib.pyplot as plt

class main(PullTweetsData):
    def tokenize(self,d):  
        result = d.split("/")
        result = list(filter(None, result))
        return result

    def prepared_Text(self,text_list):
        new_text = []
        for text in text_list:
            new_text.append(self.preprocessText(text))
        return new_text
        
    def MostWordFinder(self,keyword):
        self.connectToDB("twitter","tweets")
        vectorizer = CountVectorizer(tokenizer=self.tokenize)
        transformed_data = vectorizer.fit_transform(self.prepared_Text(self.find_tweets("keyword",keyword,"return")))
        keyword_df1 = pd.DataFrame(columns = ['word', 'count'])
        keyword_df1['word'] = vectorizer.get_feature_names_out()
        print(vectorizer.get_feature_names_out())
        keyword_df1['count'] = np.ravel(transformed_data.sum(axis=0))   
        keyword_df1.sort_values(by=['count'], ascending=False).head(10)
        return keyword_df1

TweetsCounter = main()

In [2]:
tweets = ["I/love/machine/learning", "machine/learning/is/fun", "I/am/learning/machine/learning", "I/am/a/machine/learning/engineer"]
def tokenize(d):  
        result = d.split("/")
        result = list(filter(None, result))
        print(result)
        return result

vectorizer = CountVectorizer(tokenizer=tokenize)

transformed_data = vectorizer.fit_transform(tweets)

print(vectorizer.get_feature_names_out())

X = transformed_data.toarray()

print(X)

print(np.ravel(transformed_data.sum(axis=0)))

['i', 'love', 'machine', 'learning']
['machine', 'learning', 'is', 'fun']
['i', 'am', 'learning', 'machine', 'learning']
['i', 'am', 'a', 'machine', 'learning', 'engineer']
['a' 'am' 'engineer' 'fun' 'i' 'is' 'learning' 'love' 'machine']
[[0 0 0 0 1 0 1 1 1]
 [0 0 0 1 0 1 1 0 1]
 [0 1 0 0 1 0 2 0 1]
 [1 1 1 0 1 0 1 0 1]]
[1 2 1 1 3 1 5 1 4]


/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/feature_extraction/text.py:528: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


In [2]:
from prettytable import PrettyTable

x = PrettyTable()
result = TweetsCounter.MostWordFinder("#ทรงอย่างแบด")
x.field_names = list(result.columns)

for row in result.itertuples():
    x.add_row(row[1:])

print(x)

['a' 'abet' 'adaymoodd' ... '𝒅𝒎' '𝙇𝙄𝙉𝙀' '🇺🇦']
+---------------------------------------+-------+
|                  word                 | count |
+---------------------------------------+-------+
|                   a                   |   3   |
|                  abet                 |   12  |
|               adaymoodd               |   5   |
|               adlvxlisa               |   6   |
|                  aff                  |   2   |
|        affmitsubishielectriccup       |   2   |
|                  afu                  |   20  |
|                 again                 |   5   |
|                  all                  |   6   |
|               allmaxbet               |   11  |
|               allpgslot               |   11  |
|          alwaysandforevergot          |   2   |
|               amaratjeab              |   1   |
|                  and                  |   6   |
|                  ans                  |   5   |
|                 anwxr                 |   1   |
|   

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/feature_extraction/text.py:528: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


In [4]:
%matplotlib tk

In [5]:
word_dict = {}
for i in range(0,len(result)):
  word_dict[result.word[i]]= result['count'][i]
wordcloud = WordCloud(width=1280,height=720,font_path='./SukhumvitSet-Medium.ttf',background_color ='white',max_words=70).fit_words(word_dict)
fig, ax = plt.subplots(1, 1, figsize=(16,9))
ax.imshow(wordcloud, interpolation='bilinear')
ax.axis("off")
fig.show()


: 