In [1]:
import sys
import numpy as np
sys.path.append('../')
from TwitterKeeper.Twitter_keeper import PullTweetsData
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd
from wordcloud import WordCloud
import matplotlib.pyplot as plt

class main(PullTweetsData):
    def tokenize(self,d):  
        result = d.split("/")
        result = list(filter(None, result))
        return result

    def prepared_Text(self,text_list):
        new_text = []
        for text in text_list:
            new_text.append(self.preprocessText(text))
        return new_text
        
    def MostWordFinder(self,keyword):
        self.connectToDB("twitter","tweets")
        vectorizer = CountVectorizer(tokenizer=self.tokenize)
        transformed_data = vectorizer.fit_transform(self.prepared_Text(self.find_tweets("keyword",keyword,"return")))
        keyword_df1 = pd.DataFrame(columns = ['word', 'count'])
        keyword_df1['word'] = vectorizer.get_feature_names_out()
        print(vectorizer.get_feature_names_out())
        keyword_df1['count'] = np.ravel(transformed_data.sum(axis=0))   
        keyword_df1.sort_values(by=['count'], ascending=False).head(10)
        return keyword_df1

TweetsCounter = main()

In [6]:
text = "เค้ามาบนค่ะ ครั้งที่แล้วไม่ได้แจกเพราะว่าคะแนนไม่ถึงเลย แต่ถ้าได้เอเวลตามนี้แจกแน่ๆ ขอให้ทุกคนอวยพรให้สอบได้เท่านี้ จะได้เอาแจกนะคะ😭😭😭"
TweetsCounter.preprocessText(text)

'เค้า/แจก/คะแนน/เอ/เวล/แจก/แน่ๆ/ขอให้/อวยพร/สอบ/แจก/นะคะ'

In [2]:
tweets = ["I/love/machine/learning", "machine/learning/is/fun", "I/am/learning/machine/learning", "I/am/a/machine/learning/engineer"]
def tokenize(d):  
        result = d.split("/")
        result = list(filter(None, result))
        print(result)
        return result

vectorizer = CountVectorizer(tokenizer=tokenize)

transformed_data = vectorizer.fit_transform(tweets)

print(vectorizer.get_feature_names_out())

X = transformed_data.toarray()

print(X)

print(np.ravel(transformed_data.sum(axis=0)))

['i', 'love', 'machine', 'learning']
['machine', 'learning', 'is', 'fun']
['i', 'am', 'learning', 'machine', 'learning']
['i', 'am', 'a', 'machine', 'learning', 'engineer']
['a' 'am' 'engineer' 'fun' 'i' 'is' 'learning' 'love' 'machine']
[[0 0 0 0 1 0 1 1 1]
 [0 0 0 1 0 1 1 0 1]
 [0 1 0 0 1 0 2 0 1]
 [1 1 1 0 1 0 1 0 1]]
[1 2 1 1 3 1 5 1 4]


C:\Users\nonth\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\feature_extraction\text.py:528: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


In [2]:
from prettytable import PrettyTable

x = PrettyTable()
result = TweetsCounter.MostWordFinder("#ข่าวการเมือง")
x.field_names = list(result.columns)

for row in result.itertuples():
    x.add_row(row[1:])

print(x)
# print(result.to_dict())

['aroundthailand' 'กทม' 'กม' 'กระดาน' 'กระแส' 'กลาง' 'การบริหาร' 'การพนัน'
 'การศึกษา' 'การไฟฟ้า' 'กาสิโน' 'ก้าว' 'ก้าวไกล' 'ขอให้' 'ขับ' 'ข่าว'
 'ข่าวการเมือง' 'ข้อมูล' 'คน' 'คนไทย' 'คลิป' 'คำขวัญ' 'คำถาม' 'ค่า'
 'ค่าบริการ' 'ค่ารักษา' 'งบ' 'งาน' 'งามหน้า' 'จบ' 'จังหวัด' 'จัดส่ง'
 'จันทร์' 'จีน' 'จี้' 'จ่าย' 'จ้าง' 'ชม' 'ชัชชาติ' 'ชายแดน' 'ชี้' 'ชู'
 'ช่อง' 'ซื่อ' 'ฐาน' 'ดูถูก' 'ตรวจสอบ' 'ตอบ' 'ตัวเลข' 'ตั้ม' 'ตู่' 'ต่อไป'
 'ต์' 'ถก' 'ถอย' 'ถาม' 'ถูกกฎหมาย' 'ทนาย' 'ทักษิณ' 'ทำ' 'ทำหน้าที่' 'ทีม'
 'ที่นั่ง' 'ทุน' 'ท่อง' 'ท่องเที่ยว' 'ธชง' 'นักวิชาการ' 'นายก' 'นายกฯ' 'บ'
 'บอ' 'บัญชี' 'บางตา' 'บาท' 'บิล' 'ปปช' 'ปม' 'ประชาชน' 'ประชุม' 'ประมูล'
 'ประยุทธ์' 'ประเทศ' 'ปิดประชุม' 'ป้าย' 'ผู้ว่าฯ' 'พท' 'พร' 'พรรค' 'พลอ'
 'พลัง' 'พลังงาน' 'พลเอก' 'พันธุ์' 'พิมพ์' 'พื้นที่' 'พ้น' 'ม' 'มค' 'มอบ'
 'มั่นใจ' 'มาตรา' 'มิเตอร์' 'มีสิทธิ์' 'มีอำนาจ' 'มีเงิน' 'ยง' 'ยัน' 'ยึด'
 'ยื้อ' 'ยุทธ' 'รฟท' 'รมว' 'รอง' 'รังสิ' 'รัฐบาล' 'รัตน์' 'รับปาก'
 'รายวัน' 'รายเดือน' 'ร่าง' 'ลุง' 'ล่ม' 'ล้ม' 'ล้าน' 'วิจารณ์

C:\Users\nonth\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\feature_extraction\text.py:528: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


In [3]:
%matplotlib tk

In [8]:
word_dict = {}
for i in range(0,len(result)):
  word_dict[result.word[i]]= result['count'][i]
wordcloud = WordCloud(width=1280,height=720,font_path='./SukhumvitSet-Medium.ttf',mode="RGBA",background_color ="rgba(255, 255, 255, 0)",max_words=70).fit_words(word_dict)
# fig, ax = plt.subplots(1, 1, figsize=(16,9))
# ax.imshow(wordcloud, interpolation='bilinear')
# ax.axis("off")
# fig.show()
wordcloud.to_file(filename="wordcloud.png")
